### ISSUE TITLE
[fix] 홈

### ISSUE THREAD

**Issue by 30isdead** [UMC-beilsang/beilsang-iOS#70]
# 📍 Task
### 공통

- [x] 네비게이션바 구분선 삭제

### Login

- [x]  카카오 탈퇴 고치기

### Main
- [x]  포인트 없으면 챌린지를 만들 수 없다고 알림 뜨게 하기
    → 0일때 챌린지 못만들게
    → 챌린지 만들 때 자기가 가진거보다 못하게 
- [x]  챌린지 인증 사진 신고 → 해당 챌린지 신고
- [x]  추천 챌린지 없을때 다른거 뜨게 하기 → 서버한테 말하기 ..
    → 이걸 아예.. 다른 VC로 만들어놔서 걍 뷰안에 다넣고 그거 히든 하는 식으로 다시 로직 짜야할듯? 
- [x]  챌린지 ListVC에서 맨 밑으로 가면 탭바랑 인증하기 bottombar가 겹침 → 탭바를 숨기기
    depth가 1이상이면 탭바 숨기기 
- [x]  챌린지 참여하기 누르면 홈화면으로 가서 리로드.
- [x]  인증 갤러리 아무것도없을때(시작 X or 피드 X)
- [x]  인증하기 → 홈으로 로직 루트 변경으로 수정
- [ ] #72
- [x]   MainVC 로딩 인디케이터 로직 - NotificationCenter이용 

### 마이페이지
- [x]  마이페이지 네비게이션바 흰색이 아님. . → 전체적으로 네비게이션 바 색깔 흰색으로 바꿈

# 🛠 Tracking

### 📎 LoginVC

- **accesstoken**과.. .accessToken이라…
- 그리고 토큰 삭제 로직을 좀 텀을 둬가면서 했음
    
    ```swift
    let body: Parameters = ["accesstoken": accessToken]
    ```
    
    ```swift
    MyPageService.shared.DeleteKakaoWithDraw { response in
                        print(response.message)
                        
                        DispatchQueue.main.asyncAfter(deadline: .now() + 1.5) { // 1.5초 딜레이
                            KeyChain.delete(key: Const.KeyChainKey.serverToken)
                            KeyChain.delete(key: Const.KeyChainKey.refreshToken)
                            UserDefaults.standard.setValue(nil, forKey: Const.UserDefaultsKey.deviceToken)
                            UserDefaults.standard.setValue(nil, forKey: Const.UserDefaultsKey.nickName)
                            UserDefaults.standard.setValue(nil, forKey: Const.UserDefaultsKey.existMember)
                            UserDefaults.standard.setValue(nil, forKey: Const.UserDefaultsKey.recentSearchTerms)
                            UserDefaults.standard.setValue(nil, forKey: Const.UserDefaultsKey.socialType)
                            UserDefaults.standard.synchronize()
    ```
    

### 📎 공통

- 챌린지 인증 신고하기 → 해당 챌린지 신고하기로 변경
    
![1](https://github.com/UMC-beilsang/beilsang-iOS/assets/127213160/db9c0066-d35c-4faf-89a5-e132a036c28a) | ![2](https://github.com/UMC-beilsang/beilsang-iOS/assets/127213160/9f5ad5de-e47b-4344-bc96-3d7aba3ff069)
---| ---|

### 📎 HomeMainVC, MainChallengeVC

- mainafterVC, mainBeforeVC 하나로 합침
- 오토레이아웃 셋업 함수를 네개를 짠 다음, 밑의 로직에 따라 로드함.

![3](https://github.com/UMC-beilsang/beilsang-iOS/assets/127213160/8a0aea53-faf6-44d9-89ca-dc11651ddf06) | ![4](https://github.com/UMC-beilsang/beilsang-iOS/assets/127213160/e2178886-e150-4203-bf44-f6a6902be7fe)
---| ---|

    ```swift
    if 참여중챌린지 개수 == 0{
    	챌린지 없음 뷰 로드
    }
    else{
    	챌린지 있음 뷰 로드 
    }
    
    if 추천 챌린지 개수 == 0{
    	추천 챌린지 없음 뷰 로드
    }
    else {
    	추천 챌린지 있음 뷰 로드 
    }
    ```
    
    - 코드
        
        ```swift
        // MARK: - Layout setting
        extension MainChallengeViewController {
            // 기본
            func setBasicLayout() {
                view.addSubview(participatingChallengeLabel)
                view.addSubview(recommendChallengeLabel)
                
                participatingChallengeLabel.snp.makeConstraints { make in
                    make.top.equalToSuperview().offset(24)
                    make.leading.equalToSuperview().offset(16)
                }
                
                recommendChallengeLabel.snp.makeConstraints{ make in
                    make.top.equalTo(participatingChallengeLabel.snp.bottom).offset(180)
                    make.leading.equalToSuperview().offset(16)
                }
            }
            
            //참여중인 챌린지가 없는 경우
            func setNoChallengeViewLayout(){
                view.addSubview(notParticipatingLabel)
                view.addSubview(participateChallengeButton)
        
                notParticipatingLabel.snp.makeConstraints { make in
                    make.top.equalTo(participatingChallengeLabel.snp.bottom).offset(48)
                    make.centerX.equalToSuperview()
                }
                
                participateChallengeButton.snp.makeConstraints { make in
                    make.centerX.equalToSuperview()
                    make.top.equalTo(notParticipatingLabel.snp.bottom).offset(12)
                    make.width.equalTo(240)
                    make.height.equalTo(40)
                }
            }
            
            //참여중인 챌린지가 있는 경우
            func setChallengeViewLayout() {
                view.addSubview(viewAllButton)
                view.addSubview(challengeParticipatingCollectionView)
                
                viewAllButton.snp.makeConstraints { make in
                    make.centerY.equalTo(participatingChallengeLabel.snp.centerY)
                    make.trailing.equalToSuperview().offset(-16)
                    make.width.equalTo(70)
                    make.height.equalTo(21)
                }
                
                challengeParticipatingCollectionView.snp.makeConstraints { make in
                    make.top.equalTo(participatingChallengeLabel.snp.bottom).offset(12)
                    make.leading.equalToSuperview().offset(16)
                    make.trailing.equalToSuperview().offset(-16)
                    make.height.equalTo(140)
                }
            }
            
            //추천 챌린지가 없는 경우
            func setNoRecommendChallengeViewLayout(){
                view.addSubview(notRecommendChallengeLabel)
                view.addSubview(joinChallengeButton)
        
                notRecommendChallengeLabel.snp.makeConstraints { make in
                    make.top.equalTo(recommendChallengeLabel.snp.bottom).offset(48)
                    make.centerX.equalToSuperview()
                }
                
                joinChallengeButton.snp.makeConstraints { make in
                    make.centerX.equalToSuperview()
                    make.top.equalTo(notRecommendChallengeLabel.snp.bottom).offset(12)
                    make.width.equalTo(240)
                    make.height.equalTo(40)
                }
            }
            
            //추천 챌린지가 있는 경우
            func setRecommendChallengeViewLayout() {
                view.addSubview(challengeRecommendCollectionView)
                
                challengeRecommendCollectionView.snp.makeConstraints { make in
                    make.top.equalTo(recommendChallengeLabel.snp.bottom).offset(12)
                    make.leading.equalToSuperview().offset(16)
                    make.trailing.equalToSuperview().offset(-16)
                    make.height.equalTo(140)
                }
            }
        }
        ```
        
        ```swift
        override func viewDidLoad() {
                super.viewDidLoad()
                setBasicLayout()
                nickNamerequest()
                challengeJoin(){
                    count in
                    if count == 0 {
                        self.setNoChallengeViewLayout()
                    } else {
                        self.setChallengeViewLayout()
                    }
                }
                challengeRecommend { count in
                    if count == 0 {
                        self.setNoRecommendChallengeViewLayout()
                    } else {
                        self.setRecommendChallengeViewLayout()
                    }
                }
                
                setCollectionView()
            }
        ```
        

### 📎 ChallengeListVC

- 포인트 없으면 챌린지를 만들 수 없다고 알림 뜨게 하기
    
    → 0일때 챌린지 못만들게 → 자기 현재 포인트 보여주기 
    
    ```swift
    func checkPoint() {
            MyPageService.shared.getPoint(baseEndPoint: .mypage, addPath: "/points"){
                response in
                if response.data.total < 100 {
                    self.pointAlertUp()
                    self.pointLabel2.text = String(response.data.total)
                }
                else{
                    let registerChallengeVC = RegisterFirstViewController()
                    registerChallengeVC.hidesBottomBarWhenPushed = true
                    self.navigationController?.pushViewController(registerChallengeVC, animated: true)
                }
            }
        }
    ```
 <img src="https://github.com/UMC-beilsang/beilsang-iOS/assets/127213160/a6cc971c-ee48-49da-ba61-5db0b207de4c" width="50%" height="50%"/>

### 📎 ChallengeDetailVC

- 챌린지 참여하기 누르면 홈화면으로 가서 리로드.
    - 루트VC 바꾸는 식으로 해결 → 이러니까 자동 API 통신 다시 됨

### 📎 JoinChallengeVC

- 현재 날짜 이전이면 “아직 시작되지 않았어요”, 현재 날짜 이후라면 “인증 피드가 없어요”

```swift
let dateFormatter = DateFormatter()
            dateFormatter.dateFormat = "yyyy-MM-dd"
            **dateFormatter.timeZone = TimeZone(abbreviation: "UTC")**
            
            if let date = dateFormatter.date(from: response.data.startDate) {
                // 서버에서 넘겨준 startDate를 오늘 날짜와 비교
                let today = Date()
                let result = date.compare(today)
                if result == .orderedAscending {
                    self.notStartedLabel.text = "아직 챌린지가 시작되지 않았어요👀"
                } else {
                    self.notStartedLabel.text = "아직 인증 피드가 없어요👀"
                }
            }
```

### 📎 RegisterSecondVC

- 포인트 없으면 챌린지를 만들 수 없다고 알림 뜨게 하기
    
    → 챌린지 최소 포인트가 자신이 가지고 있는 포인트보다 많으면 다음 단계로 못넘어가게 하기 
    
    ```swift
    @objc func nextButtonClicked() {
            print("다음으로")
            let pointInt = Int(pointIntLabel.text!)
            
            MyPageService.shared.getPoint(baseEndPoint: .mypage, addPath: "/points"){
                response in
                let currentPoint = response.data.total
                if (currentPoint < pointInt!){
                    self.pointAlertUp()
                    self.pointLabel2.text = String(response.data.total)
                }
                else{
                    let nextVC = RegisterThirdViewController()
                    self.navigationController?.pushViewController(nextVC, animated: true)
    
                }
            }
    ```
    <img src="https://github.com/UMC-beilsang/beilsang-iOS/assets/127213160/13a09f32-2ddc-4e8c-99e8-06486d2dff42" width="50%" height="50%"/>
    

### 📎 RegisterCertifyVC

- 인증하기 누른 뒤에, 홈으로 가는 로직 변경
    
    ```swift
    @objc func certifyButtonClicked() {
            print("인증하기")
            
            guard let image = certifyPhotoImage.image else { return }
            let imageData = image.jpegData(compressionQuality: 0.5)
            ChallengeCertifySingleton.shared.image = imageData
            ChallengeCertifySingleton.shared.review = reviewTextView.text
            
            reviewPost()
            
            ChallengeCertifySingleton.shared.resetData()
            
            if let sceneDelegate = UIApplication.shared.connectedScenes.first?.delegate as? SceneDelegate, let window = sceneDelegate.window {
                let mainVC = TabBarViewController()
                UIView.transition(with: window, duration: 1.5, options: .transitionCrossDissolve, animations: {
                    window.rootViewController = mainVC
                }, completion: nil)
            }
        }
    ```
    

### 📎 FindVC, MypageVC, HomeMainVC

- 네비게이션바 색깔 바뀌는 문제
    - 흰색으로 통일
    
    ```swift
    private func setNavigationBar() {
            self.navigationItem.titleView = attributeTitleView()
            let appearance = UINavigationBarAppearance()
            appearance.configureWithOpaqueBackground()
            appearance.backgroundColor = UIColor.white // 원하는 배경색 설정
            
            navigationController?.navigationBar.standardAppearance = appearance
            navigationController?.navigationBar.scrollEdgeAppearance = appearance
            setBackButton()
        }
    ```
   

# 💬 기타 사항
